remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Ball Classifier
description: An image classification API that classifies 10 different types of balls

author:
  name: Md. Kabin Hasan Kanchon