remote_theme : jekyll-theme-basically-basic@master
plugins:
- jekyll-remote-theme

title: Ball Classifier
description: 
A classifier that classifies 10 types of balls as given,
  1. 
    
author: 
  name: Md. Kabin Hasan Kanchon
  
    