remote_theme: daattali/beautiful-jekyll
plugins:
- jekyll-remote-theme 

title: Ball Classifier
description: An image classification API that classifies 10 different types of balls

author:
  name: Md. Kabin Hasan Kanchon

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"