remote_theme: daattali/beautiful-jekyll
plugins:
- jekyll-remote-theme 

title: Ball Classifier
description: An image classification API that classifies 10 different types of balls

author: Md. Kabin Hasan Kanchon

navbar-links:
  Home: "index.md"
  Classifier: "ball_classifier.html"